branches:
  only:
  - master
language: python
python:
  - "3.6.7"
install:
  - "pip install -r requirements.txt"
script:
  - pytest --black --cov=./ --cov-report=term-missing
  - find . -name "Solution.py" -type f -exec coverage run -p '{}' \;
  - coverage combine
  - coverage html
after_success:
  - bash <(curl -s https://codecov.io/bash) -f '*.*' -s htmlcov -t ef5aa6c1-7099-454a-a6b3-f59d68bbd8ca -n CODING_INTERVIEW_SOLUTION_APPROACHES_CODE_COVERAGE